# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
# fastlane_version "2.36.0"

default_platform :android
platform :android do

    desc "Deploy a new version to the Google Play"
    lane :deploy do
        prepareBuild
        uploadBuild
    end

    desc "Deploy a new version to the Google Play"
    lane :deployBeta do
        prepareBuild
        uploadBuildBeta
    end

    desc "Deploy a new version to the Google Play"
    lane :prepareBuild do
        projectClean
        createDebugBuild
        runUiTestCases
        takeScreenshots
        makeReleaseBuild
    end

    desc "Project clean up. Running clean"
    lane :projectClean do
        gradle(task: "clean")
    end

    desc "Creating debug build. Running assembleDebug"
    lane :createDebugBuild do
        gradle(task: "assembleDebug")
    end

    desc "UI testing. assembleDebugAndroidTest"
    lane :runUiTestCases do
        gradle(task: "assembleDebugAndroidTest")
    end

    desc "Creating screenshots. Running screengrab"
    lane :takeScreenshots do
     #   adb(command: "kill-server") #just in case
     #   adb(command: "start-server")

     #   launch the emulator and detach
     #   Process.fork {'/Users/ranaranvijaysingh/Library/Android/sdk/tools/emulator -avd
     #   Nexus_5_API_24 -no-audio  -no-window -gpu off'}
     #   sleep 40 #give the emu some boot time.
     #   adb(command: "wait-for-device")
         screengrab
    end

    desc "Creating release build. Running assembleRelease"
    lane :makeReleaseBuild do
        gradle(task: "assembleRelease")
    end

    desc "Uploading on production. Running supply(apk: './app/build/outputs/apk/app-release.apk')"
    lane :uploadBuildProduction do
        supply(apk: './app/build/outputs/apk/app-release.apk')
    end

    desc "Uploading on beta. Running supply(apk: './app/build/outputs/apk/app-release.apk')"
    lane :uploadBuildBeta do
        supply(apk: './app/build/outputs/apk/app-release.apk', track: 'beta')
    end
end